### ISSUE TITLE
Could you please update the answer for tutorial "ER diagrams" and "Database Schema"?

### ISSUE THREAD

**Issue by Helenlxy** [Marina-t/CSC343_Tutorials#1]
Could you please update the answer for "ER diagrams" and "database schema"?
Thank you so much!

**Comment by Marina-t** [comment]
Done!. You will find them under the link for [Tutorial 12](https://github.com/Marina-t/CSC343_Tutorials/tree/master/Tutorial%2012)
As noted by the commit message, those are NOT my own solutions.

Best of luck on the final
